### ISSUE TITLE
想用Aardio给py写个界面，刚看到这个转换。

### ISSUE THREAD

**Issue by wirelessren** [jim4node/py2aardio#1]
要是有完整的解决方法，那就完美了。
加油。

**Comment by jim4node** [comment]
谢谢鼓励:)
这个小工具目前只能把 python 源码转换为 aardio 源码, 并且不保证语法语义上的正确;
要写界面的话, aardio 自带的代码段:[范例程序]-[Python 语言]有教全面的 aardio 调用python 并与 python 程序互动的例子.

**Comment by jim4node** [comment]
> 要是有完整的解决方法，那就完美了。
> 加油。

谢谢鼓励:)
这个小工具目前只能把 python 源码转换为 aardio 源码, 并且不保证语法语义上的正确;
要写界面的话, aardio 自带的代码段:[范例程序]-[Python 语言]有比较丰富的例子, 全面介绍了 aardio 调用 python 并与 python 程序互动的技术和实现.

**Comment by wirelessren** [comment]
谢谢回复，看到这个范例了。您的这个程序很棒。

Jimmy CHEN ***@***.***> 于2021年4月28日周三 下午10:08写道：
